[package]
name = "texlab"
description = "LaTeX Language Server"
version = "1.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>", 
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[workspace]
members = ["./jsonrpc", "./jsonrpc_derive"]

[dependencies]
base64 = "0.10.1"
bytes = "0.4.12"
byteorder = "1"
clap = "2.33"
copy_dir = "0.1.2"
dirs = "2.0"
futures-boxed = { path = "futures_boxed" }
futures-preview = { version = "0.3.0-alpha.15", features = ["compat"] }
html2md = "0.2.9"
image = "0.21.2"
indoc = "0.3.1"
itertools = "0.8.0"
jsonrpc = { path = "jsonrpc" }
jsonrpc-derive = { path = "jsonrpc_derive" }
log = "0.4.6"
lsp-types = { git = "https://github.com/latex-lsp/lsp-types", rev = "9fcc5d9b9d3013ce84e20ef566267754d594b268", features = ["proposed"] }
nom = "5.0.0-beta2"
once_cell = "0.2.2"
path-clean = "0.1.0"
petgraph = "0.4"
regex = "1.1.9"
reqwest = "0.9.18"
runtime = "0.3.0-alpha.4"
runtime-tokio = "0.3.0-alpha.5"
serde = { version = "1.0.90", features = ["derive", "rc"] }
serde_json = "1.0.39"
serde_repr = "0.1"
stderrlog = "0.4.1"
tempfile = "3"
tokio = "0.1"
tokio-codec = "0.1"
tokio-process = "0.2.3"
tokio-stdin-stdout = "0.1"
url = "1.7.2"
url_serde = "0.2.0"
wait-timeout = "0.2.0"
walkdir = "2"

[dev-dependencies]
criterion = "0.2"

[build-dependencies]
reqwest = "0.9.18"

[[bench]]
name = "completion"
harness = false

[profile.release]
lto = true