[package]
name = "texlab"
description = "LaTeX Language Server"
version = "3.0.1"
license = "GPL-3.0"
readme = "README.md"
authors = [
    "Eric Förster <eric.foerster@outlook.com>",
    "Patrick Förster <patrick.foerster@outlook.de>",
]
edition = "2018"
homepage = "https://texlab.netlify.app"

[lib]
doctest = false

[features]
default = ["citation", "completion"]
completion = ["fuzzy-matcher"]
citation = ["bibutils-sys", "citeproc", "citeproc-db", "citeproc-io", "csl", "fnv", "html2md", "lalrpop-util", "lalrpop"]
semantic = []

[dependencies]
anyhow = "1.0.40"
bibutils-sys = { version = "0.1.1", optional = true }
byteorder = "1.4.3"
cancellation = "0.1"
cfg-if = "1.0.0"
chashmap = "2.2.2"
citeproc = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221", optional = true }
citeproc-db = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221", optional = true }
citeproc-io = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221", optional = true }
csl = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "68c7a7c16088b5d7751641ab37299ad064cdb221", optional = true }
crossbeam-channel = "0.5.1"
cstree = "0.5.0"
derive_more = "0.99.14"
encoding_rs = "0.8.28"
encoding_rs_io = "0.1.7"
fern = "0.6"
fnv = { version = "1.0", optional = true }
fuzzy-matcher = { version = "0.3.7", optional = true }
html2md = { version = "0.2.11", optional = true }
itertools = "0.10.0"
lalrpop-util = { version = "0.19.5", optional = true }
log = "0.4.14"
logos = "0.12.0"
lsp-server = "0.5"
lsp-types = "0.89.1"
multimap = "0.8.3"
notify = "5.0.0-pre.8"
once_cell = "1.8.0"
petgraph = "0.5.1"
rayon = "1.5.1"
regex = "1.5.4"
rustc-hash = "1.1.0"
serde = "1.0.126"
serde_json = "1.0.64"
serde_repr = "0.1.7"
smol_str = { version = "0.1.17", features = ["serde"] }
structopt = "0.3"
tempfile = "3.2.0"
threadpool = "1.8.1"
titlecase = "1.1.0"
url = "2.2.2"

[dev-dependencies]
indoc = "1.0.3"
insta = "1.7.1"
typed-builder = "0.9.0"
unindent = "0.1.7"

[build-dependencies]
lalrpop = { version = "0.19.5", features = ["lexer"], optional = true }

[profile.release]
lto = true